{% set name = "koopmans-kcp" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/epfl-theos/koopmans-kcp/archive/v{{ version }}.tar.gz
  sha256: 34aabc9fc4b4787a5be61d25290310e14b11a5077d19b30a30c2ad720afbb607

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - openmpi-mpifort
    - make
  host:
    - fftw
    - libblas
    - liblapack
    - openmpi
  run:
    - fftw
    - openmpi

test:
  commands:
    - test -f ${PREFIX}/bin/kcp.x

about:
  home: https://github.com/epfl-theos/koopmans-kcp
  summary: Implementation of Koopmans functionals with full orbital optimization in Quantum ESPRESSO v4.1
  description: |
    koopmans-kcp is an implementation of Koopmans functionals in Quantum
    ESPRESSO v4.1 with full orbital optimization. Instead of using this
    as a stand-alone code, it is strongly recommended you install and use
    the larger koopmans package <https://koopmans-functionals.org>.
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE
  doc_url: https://koopmans-functionals.org
  dev_url: https://github.com/epfl-theos/koopmans-kcp

extra:
  recipe-maintainers:
    - elinscott
    - nscolonna
